# container temporaire pour build l'appli
FROM node:lts-alpine AS builder

ENV VITE_S3_CLOUDFRONT=https://d1wizaxnjlzb3w.cloudfront.net
ENV VITE_NODE_ENV=staging

RUN mkdir /app
WORKDIR /app
COPY package*.json ./
RUN npm i
COPY public public
COPY components.json ./
COPY tailwind.config.js ./
COPY postcss.config.js ./
COPY index.html ./
COPY vite.config.ts ./
COPY tsconfig*.json ./
COPY src src

RUN npm run build

# container final dans lequel sera copiée l'appli une fois build
FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "5173"]