name: Compile Code & Send Images to DockerHub

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        # Add services here
        service:
          - frontend
          - backend
          - file

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_LIFTUP_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.APP_NAME }}-${{ matrix.service }}:latest

  notify-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Notify server
        run: |
          curl -X POST ${{ secrets.SERVER_IP }}/hooks/${{ secrets.UPDATE_KEY }}