name: e2e-test-workflow

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set environment variables
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_SCHEMA=${{ secrets.DB_SCHEMA }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
          echo "GATEWAY_PORT=7100" >> $GITHUB_ENV
          echo "BACKEND_HOST=liftup-test-backend" >> $GITHUB_ENV
          echo "FRONTEND_HOST=liftup-test-frontend" >> $GITHUB_ENV
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> $GITHUB_ENV

      - name: Build and run Docker Compose
        run: |
          docker-compose -f compose.e2e.yaml up -d --build

      - name: Seed the database
        run: |
          docker exec liftup-test-backend npm run seed:test

      - name: Run E2E tests
        run: |
          cd e2e
          npm install
          npm run test

      - name: Stop and clean up Docker containers
        if: always()
        run: |
          docker-compose -f compose.e2e.yaml down
