# .github/workflows/jest-tests-on-pr-dev.yml

name: Run Jest Tests on PR to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm ci

      - name: Run Jest tests
        working-directory: ./backend
        run: |
          npm test
